[tool.poetry]
name = "xlabs-hack-2024"
version = "0.1.0"
description = ""
authors = ["kirill <w_shkolenko@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fairseq = {git = "https://github.com/cyanbx/Prompt-Singer.git"}
einops = "^0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

